name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: Copy schema files
        run: |
          mkdir -p docs/schema/context docs/schema/schemas docs/schema/ontologies
          cp schema/context/personality-context.jsonld docs/schema/context/
          cp schema/schemas/personality-traits.json docs/schema/schemas/
          cp schema/ontologies/trait-vocabulary.md docs/schema/ontologies/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - uses: actions/deploy-pages@v4
