name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - name: Copy schema files
        run: |
          mkdir -p docs/schema/context docs/schema/schemas docs/schema/ontologies
          cp schema/context/personality-context.jsonld docs/schema/context/
          cp schema/schemas/personality-traits.json docs/schema/schemas/
          cp schema/schemas/personality-interview.json docs/schema/schemas/
          cp schema/schemas/mbti-type.json docs/schema/schemas/
          cp schema/schemas/dark-triad.json docs/schema/schemas/
          cp schema/schemas/mmpi-scales.json docs/schema/schemas/
          cp schema/ontologies/trait-vocabulary.md docs/schema/ontologies/
      - name: Convert index.md to HTML
        run: |
          pip install markdown --quiet
          python - <<'EOF'
          import markdown, pathlib
          md = pathlib.Path('docs/index.md').read_text()
          html = markdown.markdown(md)
          pathlib.Path('docs/index.html').write_text(f"<html><body>{html}</body></html>")
          EOF
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
      - uses: actions/deploy-pages@v4
